language: python

sudo: false

python: 3.4

services:
    - mongodb
    - elasticsearch
    - redis-server

addons:
  apt:
    sources:
    - mongodb-3.0-precise
    packages:
    - mongodb-org-server

cache:
    directories:
        - $HOME/.cache/bower
        - $HOME/.npm
        - $HOME/.pip

before_install:
    - npm config set loglevel warn 
    - npm install -g bower grunt-cli
    - export DISPLAY=:99.0 && /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1920x1080x24
    - wget -N --no-verbose 'https://storage.googleapis.com/chromium-browser-continuous/Linux_x64/353893/chrome-linux.zip' && unzip chrome-linux.zip &&
      export CHROME_BIN=`pwd`/chrome-linux/chrome && $CHROME_BIN --version ;

install:
    - npm install
    - bower install --quiet
    - cd test-server && pip install -q -r requirements.txt && cd ..
    - ./node_modules/.bin/webdriver-manager update

script:
    - grunt ci:travis
    - grunt build --server='http://127.0.0.1:5000/api' --ws='ws://127.0.0.1:5100'
    - cd test-server && (nohup honcho start & ) && cd ..
    - cd dist && (nohup python3 -m http.server 9090 & ) && cd ..
    - ./node_modules/protractor/bin/protractor protractor-conf.js
