language: python

sudo: false

python: 3.4

cache:
    directories:
        - $HOME/.cache/bower
        - $HOME/.npm
        - $HOME/.pip

before_install:
    - npm install -g bower grunt-cli
    - export DISPLAY=:99.0 && /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1920x1080x24

install:
    - npm install
    - bower install
    - cd test-server && pip install -r requirements.txt && cd ..
    - ./node_modules/.bin/webdriver-manager update

script:
    - grunt ci:travis
    - grunt build
    - cd test-server && (nohup honcho start & ) && cd ..
    - cd dist && (nohup python3 -m http.server 9000 & ) && cd ..
    - ./node_modules/protractor/bin/protractor protractor-conf.js
