language: python

python: 3.4

sudo: false

env:
    - TARGET=e2e_first_chrome
    - TARGET=e2e_second_chrome
    - TARGET=e2e_third_chrome

services:
    - mongodb
    - elasticsearch
    - redis-server

addons:
  apt:
    sources:
    - mongodb-3.0-precise
    packages:
    - mongodb-org-server

cache:
    directories:
        - $HOME/.cache/bower
        - $HOME/.cache/pip
        - $HOME/.npm

before_install:
    - npm config set loglevel warn 
    - npm install -g bower grunt-cli
    - export DISPLAY=:99.0 && /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1920x1080x24
    - wget -N --no-verbose 'https://storage.googleapis.com/chromium-browser-continuous/Linux_x64/353893/chrome-linux.zip' && unzip chrome-linux.zip &&
      export CHROME_BIN=`pwd`/chrome-linux/chrome && $CHROME_BIN --version ;


install:
    - npm install
    - bower install --quiet
    - cd test-server && pip install -q -r requirements.txt && cd ..
    - ./node_modules/.bin/webdriver-manager update

script:
    - grunt ci:travis
    - grunt build ;
      cd dist ;
      while [ ! -f index.html ]; do sleep .5; done ;
        (nohup python -m http.server 9000 & );
      cd .. ;
    - cd test-server ;
      nohup python manage.py ;
      (honcho start rest wamp & ) ;
      (nohup honcho start work & ) ;
      sleep 5 ;
      cd ..;
    - if [ "${TARGET}" != "${TARGET/e2e_first/}" ]; then
        ./node_modules/.bin/protractor-flake --node-bin node --max-attempts=3 -- protractor-conf.js --suite=a
          --stackTrace --verbose
          --capabilities.browserName "${TARGET/e2e_first_/}"
         ;
      fi
    - if [ "${TARGET}" != "${TARGET/e2e_second/}" ]; then
        ./node_modules/.bin/protractor-flake --node-bin node --max-attempts=3 -- protractor-conf.js --suite=b
          --stackTrace --verbose
          --capabilities.browserName "${TARGET/e2e_second_/}"
         ;
      fi
    - if [ "${TARGET}" != "${TARGET/e2e_third/}" ]; then
        ./node_modules/.bin/protractor-flake --node-bin node --max-attempts=3 -- protractor-conf.js --suite=c
          --stackTrace --verbose
          --capabilities.browserName "${TARGET/e2e_third_/}"
         ;
      fi

after_script:
    - killall -9 python
